### ISSUE TITLE
There is a problem

### ISSUE THREAD

**Issue by PuddSV** [fred41/G940#1]
Good afternoon
I have a problem with this G940 driver
I can't make it, errors occur
g++  -march=native -O3 -std=c++0x -c g940.c
g940.c: In function ‘int g940_create_uinput()’:
g940.c:184:22: error: aggregate ‘g940_create_uinput()::uinput_setup uinp’ has incomplete type and cannot be defined
  struct uinput_setup uinp;
                      ^
g940.c:185:26: error: aggregate ‘g940_create_uinput()::uinput_abs_setup uabs’ has incomplete type and cannot be defined
  struct uinput_abs_setup uabs;
                          ^
g940.c:214:12: error: ‘UI_ABS_SETUP’ was not declared in this scope
  ioctl(fd, UI_ABS_SETUP, &uabs);
            ^
g940.c:269:22: error: ‘UI_DEV_SETUP’ was not declared in this scope
  if (ret = ioctl(fd, UI_DEV_SETUP, &uinp))
                      ^
g940.c: In function ‘int main(int, char**)’:
g940.c:414:52: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("libusb_get_device_list failed: %d\n", cnt);
                                                    ^
g940.c:417:34: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
  printf("device count: %d\n", cnt);
                                  ^
g940.c: In function ‘void g940_process_report(int, uint32_t*)’:
g940.c:321:39: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
    write(ui_fd, &event, sizeof(event));
                                       ^
g940.c:327:39: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
    write(ui_fd, &event, sizeof(event));
                                       ^
g940.c:337:41: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
      write(ui_fd, &event, sizeof(event));
                                         ^
g940.c:340:41: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
      write(ui_fd, &event, sizeof(event));
                                         ^
g940.c:359:41: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
      write(ui_fd, &event, sizeof(event));
                                         ^
g940.c:376:41: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
      write(ui_fd, &event, sizeof(event));
                                         ^
g940.c:386:37: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
  write(ui_fd, &event, sizeof(event));
                                     ^
Makefile:7: ошибка выполнения рецепта для цели «g940.o»
make: *** [g940.o] Ошибка 1 
Version linux mint 18.3

I did everything according to the instructions from Readme but still the driver is not installed
Help I'm new to linux programming I just want to use g940 for War Thunder

P s Sorry for my English this is a translation

**Comment by PuddSV** [comment]
I was looking at the code and it turned out that two structures were not created input_setup and uinput_abs_setup Where are they ? They are not in any header file p S Sorry for my English

**Comment by PuddSV** [comment]
when you run the driver via the terminal (./g940), the following message appears
found G940 device!
ioctl UI_DEV_SETUP failed: -1
ioctl UI_DEV_CREATE failed: -1

**Comment by fred41** [comment]
So you apparently managed to build the driver. Did you check/install the udev rules for user permissions?
